int quote_num=32;
char *quotes[]={
"When the going gets tough, the tough turn pro. - Hunter S. Thompson\n",
"What is true is what I can't help believing. - Oliver Wendell Holmes, Jr.\n",
"Computers are very sophisticated idiots. - Doctor, ROBOT\n",
"Talk sense to a fool and he calls you foolish. - Euripides\n",
"The cure for boredom is curiosity. There is no cure for curiosity. - Ellen Parr\n",
"The greatest pleasure in life is doing what people say you cannot do. - Walter Bagehot\n",
"Only two things are infinite, the universe and human stupidity, and I'm not sure about the former. - Albert Einstein\n",
"Most people would sooner die than think; in fact, they do so. - Bertrand Russell\n",
"Imagination is more important than knowledge. - Albert Einstein\n",
"Nixon's motto was: If two wrongs don't make a right, try three. - Norman Cousins\n", 
"640K of RAM ought to be enough for anybody. - Bill Gates\n",
"The world will only need 5 computers. - Thomas Watson\n",
"Life is like a box of chocolates, you never know what your goina get. - Forest Gump\n",
"A Computer is only as good as its user. - Scott Rosendahl\n",
"Time is a great teacher, but unfortunately it kills all its pupils. - Hector Berlioz\n",
"Friendship is like money, easier made than kept. -Samuel Butler\n",
"I either want less corruption, or more chance to participate in it. -Ashleigh Brilliant\n", 
"In time of war the first casualty is truth. -Boake Carter\n", 
"I like pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals. -Winston Churchill\n", 
"Real knowledge is to know the extent of one's ignorance -Confucius\n",
"We have two ears and one mouth so that we can listen twice as much as we speak. -Epictetus\n", 
"When in doubt, move a peon. -Jose Lupe\n", 
"Believe those who are seeking the truth; doubt those who find it. -Andr Gide\n",
"No tears, It's a waste of good suffering. -Pinhead\n", 
"Those who stand for nothing fall for anything. -Alex Hamilton\n", 
"The measure of a man is what he does with power. - Pittacus\n",
"I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.  - Albert Einstein\n", 
"I never think of the future - it comes soon enough. - Albert Einstein\n", 
"If I had only known, I would have been a locksmith. - Albert Einstein\n", 
"The secret to creativity is knowing how to hide your sources. - Albert Einstein\n", 
"If the facts don't fit the theory, change the facts. - Albert Einstein\n", 
"The important thing is not to stop questioning. - Albert Einstein\n" 
};
